---
categories: techonology
layout: post
---

# 遇到问题

开发的时候遇到一个问题，我在服务提供方抛出了一个业务异常，里面包含了异常的原因。

但是在服务消费方，我不会处理这个异常，而是由框架将异常信息提取出来返回给前端。

但是在实际开发的时候发现，服务消费方抛出的异常变成了RuntimeException，而原先的异常类型消失了。

# 解决方案

参考了一些博客后，我发现了下面方式：

- 将异常声明标注在接口上。
- 将异常类移动到接口包里。

上面的两种方案任选一种就可以完美解决这个问题了，异常会以争取的类型出现在服务消费方。

# 参考博客

- [https://blog.csdn.net/mj158518/article/details/51228649](https://blog.csdn.net/mj158518/article/details/51228649)
